name: Count the rows in a file

on:
  workflow_dispatch:

jobs:
  count_rows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Count rows
      run: |
        echo "ROWS=`wc -l test.csv | cut -d' ' -f1`" >> $GITHUB_ENV
    - name: Show count
      run: |
        echo ${{ env.ROWS }}

