name: Store a number

on:
  workflow_dispatch:
    inputs:
      a_number:
        description: 'A number'
        required: true
        type: string

jobs:
  store_number:
    runs-on: ubuntu_latest
    steps:
    - name: Echo number
      run: echo ${{ inputs.a_number }}
