name: Store a number

on:
  workflow_dispatch:
    inputs:
      a_number:
        description: 'A number'
        required: true
        type: string

jobs:
  store_number:
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install jq
    - name: Echo number
      run: echo ${{ inputs.a_number }}
    - name: Show file
      run: jq . data.json

