name: Store a number

on:
  workflow_dispatch:
    inputs:
      a_number:
        description: 'A number'
        required: true
        type: string

jobs:
  store_number:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install jq
    - name: Show file
      run: jq . data.json
    - name: Add the data
      run: |
        DATE=`date -Iseconds`
        jq --arg DATE "$DATE" '.data += [{ "number" : "${{ inputs.a_number }}", "date" : $DATE }]' data.json > newdata.json
        mv newdata.json data.json
    - name: Show file again
      run: jq . data.json
    - name: Commit data file
      run: |
        GIT_STATUS=$(git status --porcelain)
        echo $GIT_STATUS
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add data.json
        if [ "$GIT_STATUS" != "" ]; then git commit -m "Automated data storage"; fi
        if [ "$GIT_STATUS" != "" ]; then git push; fi
