name: Test

on:
  workflow_dispatch:

jobs:
  test:
    uses: PerlToolsTeam/github_workflows/.github/workflows/cpan-test-new.yml@main
    with:
      os: "[ 'ubuntu-latest' ]"
      perl_version: "[ 'latest' ]"
      testing_contexts: "[ 'foo' ]"

